# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Dec  6 00:03:49 2024
# ------------------------------------------------

package:
  name: libxml2
  version: 2.13.5
source:
  patches:
    - 0002-Make-and-install-a-pkg-config-file-on-Windows.patch
  sha256: 37cdec8cd20af8ab0decfa2419b09b4337c2dbe9da5615d2a26f547449fecf2a
  url: https://gitlab.gnome.org/GNOME/libxml2/-/archive/v2.13.5/libxml2-v2.13.5.tar.gz
build:
  number: '1'
  run_exports:
    - libxml2 >=2.13.5,<3.0a0
  string: h178c5d8_1
requirements:
  build:
    - autoconf 2.71 pl5321hed12c24_1
    - automake 1.17 pl5321h694c41f_0
    - clang_bootstrap_osx-arm64 18.1.8 hf1725c4_23
    - libiconv 1.17 hd75f5a5_2
    - libtool 2.4.7 hf036a51_1
    - m4 1.4.18 haf1e3a3_1001
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - perl 5.32.1 7_h10d778d_perl5
    - pkg-config 0.29.2 hf7e621a_1009
  host:
    - icu 75.1 hfee45f7_0
    - libiconv 1.17 h0d3ecfb_2
    - liblzma 5.6.3 h39f12f2_1
    - liblzma-devel 5.6.3 h39f12f2_1
    - libzlib 1.3.1 h8359307_2
    - zlib 1.3.1 h8359307_2
  run:
    - __osx >=11.0
    - icu >=75.1,<76.0a0
    - libiconv >=1.17,<2.0a0
    - liblzma >=5.6.3,<6.0a0
    - libzlib >=1.3.1,<2.0a0
  run_constrained: []
test:
  commands:
    - echo on
    - xmllint test.xml
    - mkdir -p "${PREFIX}/etc/xml"
    - cp   test_catalog.xml "${PREFIX}/etc/xml/catalog"
    - xmlcatalog "" "http://www.w3.org/2001/xml.xsd" | grep -x -F -e "file://test-uri-override"
    - rm  "${PREFIX}/etc/xml/catalog"
    - xmlcatalog "" "test-id" | grep -x -F -e "No entry for URI test-id"
    - xmlcatalog "test_catalog.xml" "test-id" | grep -x -F -e "file://test-uri"
    - export XML_CATALOG_FILES="file://$(pwd)/test_catalog.xml"
    - xmlcatalog "" "test-id" | grep -x -F -e "file://test-uri"
    - xmlcatalog "" "http://www.w3.org/2009/01/xml.xsd" | grep -x -F -e "No entry
      for URI http://www.w3.org/2009/01/xml.xsd"
  files:
    - test.xml
    - test_catalog.xml
  requires:
    - ripgrep
about:
  description: 'Though libxml2 is written in C a variety of language

    bindings make it available in other environments.

    '
  dev_url: https://git.gnome.org/browse/libxml2/
  doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/devhelp/index.html
  doc_url: http://xmlsoft.org/html/index.html
  home: http://xmlsoft.org/
  license: MIT
  license_family: MIT
  license_file: Copyright
  summary: The XML C parser and toolkit of Gnome
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241205.5.1
  recipe-maintainers:
    - gillins
    - isuruf
    - jakirkham
    - jschueller
    - msarahan
    - ocefpaf
    - scopatz
  remote_url: https://github.com/conda-forge/libxml2-feedstock
  sha: 3172b384091b12933ff3cebef2dd856ba208d612
