# This file created by conda-build 25.1.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Jan 26 14:28:21 2025
# ------------------------------------------------

package:
  name: pip
  version: '25.0'
source:
  sha256: 8e0a97f7b4c47ae4a494560da84775e9e2f671d415d8d828e052efefb206b30b
  url: https://pypi.org/packages/source/p/pip/pip-25.0.tar.gz
build:
  disable_pip: true
  entry_points:
    - pip = pip._internal.cli.main:main
    - pip3 = pip._internal.cli.main:main
  noarch: python
  number: '0'
  string: pyh8b19718_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.12.14 hbcca054_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libexpat 2.6.4 h5888daf_0
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.3 hb9d3cd8_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.48.0 hee588c1_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_2
    - openssl 3.4.0 h7b32b05_1
    - python 3.12.8 h9e4cc4f_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.8.0 pyhff2d567_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2025a h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - python >=3.9,<3.13.0a0
    - setuptools
    - wheel
test:
  commands:
    - pip -h
    - pip list
  imports:
    - pip
  requires:
    - python 3.9.*
about:
  dev_url: https://github.com/pypa/pip
  doc_url: https://pip.pypa.io/en/stable/
  home: https://pip.pypa.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250126.2.1
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/pip-feedstock
  sha: 2acbbf6ae7179d62273576bb17021c39cac7836a
