# This file created by conda-build 25.1.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jan 25 10:28:36 2025
# ------------------------------------------------

package:
  name: conda-libmamba-solver
  version: 25.1.1
source:
  folder: src/
  sha256: 38d8b46d4890b8ebd948b4b2d9761f18d18d6fa4bef87f19bdad0a6f8e5371c8
  url: https://github.com/conda/conda-libmamba-solver/archive/25.1.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/conda-libmamba-solver_1737800978214/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install src/ -vv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=25.1.1
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.12.14 hbcca054_0
    - editables 0.5 pyhd8ed1ab_1
    - hatch-vcs 0.4.0 pyhd8ed1ab_1
    - hatchling 1.27.0 pypyhd8ed1ab_0
    - importlib-metadata 8.6.1 pyha770c72_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libffi 3.4.2 h7f98852_5
    - libgcc 14.2.0 h77fa898_1
    - libgcc-ng 14.2.0 h69a702a_1
    - libgomp 14.2.0 h77fa898_1
    - liblzma 5.6.3 hb9d3cd8_1
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.48.0 hee588c1_1
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_2
    - openssl 3.4.0 h7b32b05_1
    - packaging 24.2 pyhd8ed1ab_2
    - pathspec 0.12.1 pyhd8ed1ab_1
    - pip 24.3.1 pyh8b19718_2
    - pluggy 1.5.0 pyhd8ed1ab_1
    - python 3.9.21 h9c0c6dc_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 75.8.0 pyhff2d567_0
    - setuptools-scm 8.1.0 pyhd8ed1ab_1
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.2.1 pyhd8ed1ab_1
    - trove-classifiers 2025.1.15.22 pyhd8ed1ab_0
    - typing-extensions 4.12.2 hd8ed1ab_1
    - typing_extensions 4.12.2 pyha770c72_1
    - tzdata 2025a h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zipp 3.21.0 pyhd8ed1ab_1
  run:
    - boltons >=23.0.0
    - conda >=23.7.4
    - libmambapy >=2.0.0
    - python >=3.9
test:
  commands:
    - conda create -n test --dry-run scipy --solver=libmamba
    - CONDA_SOLVER=libmamba conda create -n test --dry-run scipy
  imports:
    - conda_libmamba_solver
  requires:
    - python 3.9.*
about:
  dev_url: https://github.com/conda/conda-libmamba-solver
  doc_url: https://conda.github.io/conda-libmamba-solver/
  home: https://github.com/conda/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: The fast mamba solver, now in conda!
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250125.1.1
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
  remote_url: https://github.com/conda-forge/conda-libmamba-solver-feedstock
  sha: 940a4e293d2c2d366d87236f1dabe76c70fc9e73
