# This file created by conda-build 25.1.1
# ------------------------------------------------

package:
  name: libsqlite
  version: 3.48.0
source:
  patches: null
  sha256: ac992f7fca3989de7ed1fe99c16363f848794c8c32a158dafd4eb927a2e02fd5
  url: https://www.sqlite.org/2025/sqlite-autoconf-3480000.tar.gz
build:
  number: 1
  run_exports:
    - libsqlite >=3.48.0,<4.0a0
  string: h3f77e49_1
requirements:
  build:
    - ca-certificates 2024.12.14 h8857fd0_0
    - cctools_osx-64 1010.6 h00edd4c_2
    - cctools_osx-arm64 1010.6 h71f0a72_2
    - clang 18.1.8 default_h179603d_5
    - clang-18 18.1.8 default_h0c94c6a_5
    - clang_impl_osx-arm64 18.1.8 hadf8e89_23
    - clang_osx-arm64 18.1.8 h1728699_23
    - clangxx 18.1.8 default_h179603d_5
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - ld64_osx-64 951.9 hc8d1a19_2
    - ld64_osx-arm64 951.9 h148c8d5_2
    - libclang-cpp18.1 18.1.8 default_h0c94c6a_5
    - libcxx 19.1.7 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_7
    - libiconv 1.17 hd75f5a5_2
    - libllvm18 18.1.8 h9ce406d_2
    - liblzma 5.6.3 hd471939_1
    - libtool 2.4.7 hf036a51_1
    - libxml2 2.13.5 he8ee3e7_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 h9ce406d_2
    - llvm-tools-18 18.1.8 h9ce406d_2
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_2
    - openssl 3.4.0 hc426f3f_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.6 h915ae27_0
  host:
    - libzlib 1.3.1 h8359307_2
    - zlib 1.3.1 h8359307_2
  run:
    - __osx >=11.0
    - libzlib >=1.3.1,<2.0a0
test:
  commands:
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  dev_url: https://github.com/mackyle/sqlite
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  doc_url: http://www.sqlite.org/docs.html
  home: http://www.sqlite.org/
  license: Unlicense
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250122.2.1
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
  remote_url: https://github.com/conda-forge/sqlite-feedstock
  sha: dc768a14f936ba3e2fd8a93f914e84da1fbbc7d5
