# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Mar 15 13:43:43 2023
# ------------------------------------------------

package:
  name: cpp-expected
  version: 1.1.0
source:
  sha256: 1db357f46dd2b24447156aaf970c4c40a793ef12a8a9c2ad9e096d9801368df6
  url: https://github.com/TartanLlama/expected/archive/v1.1.0.tar.gz
build:
  number: '0'
  string: hffc8910_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.18.1 h0d85af4_0
    - ca-certificates 2022.12.7 h033912b_0
    - cctools_osx-64 973.0.1 hcc6d90d_11
    - cctools_osx-arm64 973.0.1 hfd1dfa6_11
    - clang 14.0.6 h694c41f_0
    - clang-14 14.0.6 default_h55ffa42_0
    - clang_osx-arm64 14.0.6 he41d1a2_4
    - clangxx 14.0.6 default_h55ffa42_0
    - clangxx_osx-arm64 14.0.6 h748fd88_4
    - cmake 3.26.0 h4032537_0
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - expat 2.5.0 hf0c8a7f_0
    - krb5 1.20.1 h049b76e_0
    - ld64_osx-64 609 hfd63004_11
    - ld64_osx-arm64 609 h566df06_11
    - libclang-cpp14 14.0.6 default_h55ffa42_0
    - libcurl 7.88.1 h6df9250_0
    - libcxx 15.0.7 h71dddab_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libllvm14 14.0.6 h5b596cc_1
    - libnghttp2 1.52.0 he2ab024_0
    - libssh2 1.10.0 h47af595_3
    - libuv 1.44.2 hac89ed1_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 h5b596cc_1
    - make 4.3 h22f3db7_1
    - ncurses 6.3 h96cf925_1
    - openssl 3.1.0 hfd90126_0
    - rhash 1.4.3 hac89ed1_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zlib 1.2.13 hfd90126_4
    - zstd 1.5.2 hbc0c0cd_6
  host:
    - libcxx 15.0.7 h75e25f2_0
  run:
    - libcxx >=14.0.6
test:
  commands:
    - test -f ${PREFIX}/include/tl/expected.hpp
    - test -f ${PREFIX}/share/cmake/tl-expected/tl-expected-config.cmake
    - test -f ${PREFIX}/share/cmake/tl-expected/tl-expected-config-version.cmake
about:
  description: C++11/14/17 std::expected with functional-style extensions
  dev_url: https://github.com/TartanLlama/expected
  doc_url: https://github.com/TartanLlama/expected#readme
  home: https://github.com/TartanLlama/expected
  license: CC0-1.0
  license_file: LICENSE
  summary: C++11/14/17 std::expected with functional-style extensions
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - JohanMabille
    - wolfv
