# This file created by conda-build 25.1.1
# ------------------------------------------------

package:
  name: libmamba
  version: 2.0.6
source:
  sha256: e0f3c0b7b055af36a7a1fb2ec783591df4a5cdcfe6df518963276f03c3f3e2ad
  url: https://github.com/mamba-org/mamba/archive/refs/tags/2.0.6.tar.gz
build:
  ignore_run_exports:
    - spdlog
  number: 0
  run_exports:
    - libmamba >=2.0.6,<2.1.0a0
  string: hdf44a08_0
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - c-ares 1.34.4 hf13058a_0
    - ca-certificates 2025.1.31 h8857fd0_0
    - cctools_osx-64 1010.6 hd19c6af_3
    - cctools_osx-arm64 1010.6 hd9414f1_3
    - clang 18.1.8 default_h576c50e_7
    - clang-18 18.1.8 default_h3571c67_7
    - clang_impl_osx-arm64 18.1.8 hadf8e89_23
    - clang_osx-arm64 18.1.8 h1728699_23
    - clangxx 18.1.8 default_heb2e8d1_7
    - clangxx_impl_osx-arm64 18.1.8 hd2305f4_23
    - clangxx_osx-arm64 18.1.8 h1728699_23
    - cmake 3.31.5 h477996e_0
    - compiler-rt 18.1.8 h1020d70_1
    - compiler-rt_osx-64 18.1.8 hf2b8a54_1
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 951.9 h33512f0_3
    - ld64_osx-arm64 951.9 h0ae773b_3
    - libclang-cpp18.1 18.1.8 default_h3571c67_7
    - libcurl 8.11.1 h5dec5d8_0
    - libcxx 19.1.7 hf95d169_0
    - libcxx-devel 18.1.8 h7c275be_7
    - libedit 3.1.20250104 pl5321ha958ccf_0
    - libev 4.33 h10d778d_2
    - libexpat 2.6.4 h240833e_0
    - libiconv 1.17 hd75f5a5_2
    - libllvm18 18.1.8 hc29ff6c_3
    - liblzma 5.6.4 hd471939_0
    - libnghttp2 1.64.0 hc7306c3_0
    - libssh2 1.11.1 h3dc7d44_0
    - libuv 1.50.0 h4cb831e_0
    - libxml2 2.13.5 he8ee3e7_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 18.1.8 hc29ff6c_3
    - llvm-tools-18 18.1.8 hc29ff6c_3
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - ncurses 6.5 h0622a9a_3
    - ninja 1.12.1 h3c5361c_0
    - openssl 3.4.0 hc426f3f_1
    - rhash 1.4.5 ha44c9a9_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.6 h915ae27_0
  host:
    - bzip2 1.0.8 h99b78c6_7
    - c-ares 1.34.4 h5505292_0
    - ca-certificates 2025.1.31 hf0a4a13_0
    - cli11 2.4.2 h286801f_0
    - cpp-expected 1.1.0 hffc8910_0
    - fmt 11.0.2 h420ef59_0
    - icu 75.1 hfee45f7_0
    - krb5 1.21.3 h237132a_0
    - libarchive 3.7.7 h3b16cec_3
    - libcurl 8.11.1 h73640d1_0
    - libcxx 19.1.7 ha82da77_0
    - libedit 3.1.20250104 pl5321hafb1f1b_0
    - libev 4.33 h93a5062_2
    - libiconv 1.17 h0d3ecfb_2
    - liblzma 5.6.4 h39f12f2_0
    - libnghttp2 1.64.0 h6d7220d_0
    - libsolv 0.7.30 h6c9b7f8_0
    - libssh2 1.11.1 h9cc3647_0
    - libxml2 2.13.5 h178c5d8_1
    - libzlib 1.3.1 h8359307_2
    - lz4-c 1.10.0 h286801f_1
    - lzo 2.10 h93a5062_1001
    - ncurses 6.5 h5e97a16_3
    - nlohmann_json 3.11.3 h00cdb27_1
    - openssl 3.4.0 h81ee809_1
    - reproc 14.2.5.post0 h5505292_0
    - reproc-cpp 14.2.5.post0 h286801f_0
    - simdjson 3.12.0 ha393de7_0
    - spdlog 1.15.1 hed1c2b2_0
    - yaml-cpp 0.8.0 h13dd4ca_0
    - zstd 1.5.6 hb46c0d2_0
  run:
    - __osx >=11.0
    - cpp-expected >=1.1.0,<1.2.0a0
    - fmt >=11.0.2,<11.1.0a0
    - fmt >=11.0.2,<12.0a0
    - libarchive >=3.7.7,<3.8.0a0
    - libcurl >=8.11.1,<9.0a0
    - libcxx >=18
    - libsolv >=0.7.30,<0.7.31.0a0
    - libsolv >=0.7.30,<0.8.0a0
    - nlohmann_json >=3.11.3,<3.12.0a0
    - openssl >=3.4.0,<4.0a0
    - reproc >=14.2,<15.0a0
    - reproc >=14.2.5.0inf.0,<14.3.0a0
    - reproc-cpp >=14.2,<15.0a0
    - reproc-cpp >=14.2.5.0inf.0,<14.3.0a0
    - simdjson >=3.12.0,<3.13.0a0
    - spdlog >=1.15.1,<1.16.0a0
    - yaml-cpp >=0.8.0,<0.9.0a0
    - zstd >=1.5.6,<1.6.0a0
test:
  commands:
    - test ! -f "${PREFIX}/etc/profile.d/mamba.sh"
    - test -d ${PREFIX}/include/mamba
    - test -f ${PREFIX}/include/mamba/version.hpp
    - test -f ${PREFIX}/lib/cmake/libmamba/libmambaConfig.cmake
    - test -f ${PREFIX}/lib/cmake/libmamba/libmambaConfigVersion.cmake
    - test -e ${PREFIX}/lib/libmamba${SHLIB_EXT}
    - cat $PREFIX/include/mamba/version.hpp | grep "LIBMAMBA_VERSION_MAJOR 2"
    - cat $PREFIX/include/mamba/version.hpp | grep "LIBMAMBA_VERSION_MINOR 0"
    - cat $PREFIX/include/mamba/version.hpp | grep "LIBMAMBA_VERSION_PATCH 6"
about:
  description: '


    [![Build Status](https://github.com/mamba-org/mamba/workflows/CI/badge.svg)](https://github.com/mamba-org/mamba/actions)

    [![Join the Gitter Chat](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/mamba-org/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

    [![docs](https://readthedocs.org/projects/mamba/badge/?version=latest&style=flat)](https://mamba.readthedocs.io/en/latest)


    `mamba` is a reimplementation of the conda package manager in C++.


    - parallel downloading of repository data and package files using multi-threading

    - libsolv for much faster dependency solving, a state of the art library used
    in the RPM package manager of Red Hat, Fedora and OpenSUSE

    - core parts of `mamba` are implemented in C++ for maximum efficiency


    At the same time, `mamba` utilizes the same command line parser, package installation
    and deinstallation code and transaction verification routines as `conda` to stay
    as compatible as possible.


    Mamba is part of a bigger ecosystem to make scientific packaging more sustainable.
    You can read our [announcement blog post](https://medium.com/@QuantStack/open-software-packaging-for-science-61cecee7fc23).

    The ecosystem also consists of `quetz`, an open source `conda` package server
    and `boa`, a fast `conda` package builder.




    Please refer to the [`mamba` and `micromamba` installation guide](https://mamba.readthedocs.io/en/latest/installation.html)
    in the documentation.




    `mamba` and `micromamba` come with features on top of stock `conda`.




    To efficiently query repositories and query package dependencies you can use `mamba
    repoquery` or `micromamba repoquery`.

    See the [repoquery documentation](https://mamba.readthedocs.io/en/latest/user_guide/mamba.html#repoquery)
    for details.




    `micromamba` can be used to install lock files generated by [conda-lock](https://conda-incubator.github.io/conda-lock/)
    without having to install `conda-lock`. Simply invoke e.g. `micromamba create
    -n my-env -f conda-lock.yml` with an environment lockfile named `*-lock.yml` or
    `*-lock.yaml`.

    '
  dev_url: https://github.com/mamba-org/mamba
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A fast drop-in alternative to conda, using libsolv for dependency resolution
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250204.6.1
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - ericmjl
    - jjerphan
    - wolfv
  remote_url: https://github.com/conda-forge/mamba-feedstock
  sha: 4ee032c8d331371d3e1e53a533e3684d1428b318
