# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Aug 14 16:02:03 2024
# ------------------------------------------------

package:
  name: nlohmann_json
  version: 3.11.3
source:
  sha256: 0d8ef5af7f9794e3263480193c491549b2ba6cc74bb018906202ada498a79406
  url: https://github.com/nlohmann/json/archive/v3.11.3.tar.gz
build:
  ignore_run_exports:
    - clangxx_osx-arm64 16.*
    - macosx_deployment_target_osx-arm64 11.0.*
  number: '1'
  string: h00cdb27_1
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - c-ares 1.33.0 h51dda26_0
    - ca-certificates 2024.7.4 h8857fd0_0
    - cctools_osx-64 986 h303a5ab_3
    - cctools_osx-arm64 986 h458f0ca_3
    - clang 16.0.6 default_h179603d_11
    - clang-16 16.0.6 default_h0c94c6a_11
    - clang_impl_osx-arm64 16.0.6 ha81d56d_19
    - clang_osx-arm64 16.0.6 h40be2b1_19
    - clangxx 16.0.6 default_h179603d_11
    - clangxx_impl_osx-arm64 16.0.6 h4a79b72_19
    - clangxx_osx-arm64 16.0.6 h40be2b1_19
    - cmake 3.30.2 h749d262_0
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 75.1 h120a0e1_0
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 711 h04ffbf3_3
    - ld64_osx-arm64 711 ha337116_3
    - libclang-cpp16 16.0.6 default_h0c94c6a_11
    - libcurl 8.9.1 hfcf2730_0
    - libcxx 18.1.8 heced48a_4
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 h10d778d_2
    - libexpat 2.6.2 h73e2aa4_0
    - libiconv 1.17 hd75f5a5_2
    - libllvm16 16.0.6 hbedff68_3
    - libnghttp2 1.58.0 h64cf6d3_1
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.48.0 h67532ce_0
    - libxml2 2.12.7 heaf3512_4
    - libzlib 1.3.1 h87427d6_1
    - llvm-tools 16.0.6 hbedff68_3
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - make 4.3 h22f3db7_1
    - ncurses 6.5 h5846eda_0
    - openssl 3.3.1 h87427d6_2
    - rhash 1.4.4 h0dc2134_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - libcxx 18.1.8 h5a72898_4
  run:
    - __osx >=11.0
    - libcxx >=16
test:
  commands:
    - test -d ${PREFIX}/include/nlohmann
    - test -f ${PREFIX}/include/nlohmann/json.hpp
    - test -f ${PREFIX}/include/nlohmann/json_fwd.hpp
    - test -f ${PREFIX}/share/cmake/nlohmann_json/nlohmann_jsonConfig.cmake
    - test -f ${PREFIX}/share/cmake/nlohmann_json/nlohmann_jsonConfigVersion.cmake
    - test -f ${PREFIX}/share/cmake/nlohmann_json/nlohmann_jsonTargets.cmake
about:
  description: JSON for Modern C++ is a C++11 JSON parser.
  dev_url: http://github.com/nlohmann/json
  doc_url: http://nlohmann.github.io/json/
  home: http://github.com/nlohmann/json
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: JSON for Modern C++
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240814.1.1
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - constantinpape
    - wolfv
  remote_url: https://github.com/conda-forge/nlohmann_json-feedstock
  sha: 2dffba64be440c4372904c63b2647e0722c1deaf
